### PR TITLE
Packaging refactor

### PR DESCRIPTION
**Pull request by ghost**
see https://github.com/adamantii/objection.py/commit/91a792ee3878067f57eee145f53c3e8573f67526 for explanation

### CODE REVIEW

**Comment by ghost** [comment]
Also i have an excuse for pushing the branch really late: i was doing other things

**Comment by ghost** [comment]
closes https://github.com/adamantii/objection.py/issues/4

**Comment by ghost** [comment]
most of the changes to the objection.py are linter stuff you can revert them if you want to

**Review by adamantii — APPROVED** [review]
it works

\- (best review ever)

**Pull request merged**
